import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../screens/constants/colors.dart';
import '../../services/summary_service.dart';

class StudySheet extends StatefulWidget {
  final String subject;

  // photoCount is set for whole-folder mode, null for selection mode
  final int? photoCount;

  // photoPaths is set for selection mode, null for whole-folder mode
  final List<String>? photoPaths;

  const StudySheet({
    super.key,
    required this.subject,
    required this.photoCount,
    required this.photoPaths,
  });

  @override
  State<StudySheet> createState() => _StudySheetState();
}

class _StudySheetState extends State<StudySheet>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;
  StudyMaterial? _material;
  bool _isLoading = true;
  String _statusMsg = 'Starting...';

  // tracks which flashcard is currently flipped, -1 means none
  int _flippedIndex = -1;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 3, vsync: this);
    _generate();
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  Future<void> _generate() async {
    final isSelection = widget.photoPaths != null;

    final result = isSelection
        ? await SummaryService.getForSelection(
            photoPaths: widget.photoPaths!,
            subject: widget.subject,
            onStatus: (s) {
              if (mounted) setState(() => _statusMsg = s);
            },
          )
        : await SummaryService.getForFolder(
            subject: widget.subject,
            photoCount: widget.photoCount!,
            onStatus: (s) {
              if (mounted) setState(() => _statusMsg = s);
            },
          );

    if (mounted) {
      setState(() {
        _material = result;
        _isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.fromLTRB(12, 60, 12, 12),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(24),
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Container(
            width: 40,
            height: 4,
            margin: const EdgeInsets.only(top: 12, bottom: 16),
            decoration: BoxDecoration(
              color: Colors.grey.shade300,
              borderRadius: BorderRadius.circular(2),
            ),
          ),
          Padding(
            padding: const EdgeInsets.fromLTRB(20, 0, 20, 16),
            child: Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: const Color(0xFF035955).withOpacity(0.1),
                    borderRadius: BorderRadius.circular(10),
                  ),
                  child: const Icon(Icons.auto_awesome_rounded,
                      color: Color(0xFF035955), size: 18),
                ),
                const SizedBox(width: 10),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        widget.photoPaths != null
                            ? 'Study — ${widget.photoPaths!.length} selected'
                            : 'Study — ${widget.subject}',
                        style: const TextStyle(
                            fontWeight: FontWeight.bold,
                            fontSize: 15,
                            color: AppColors.bodyText),
                      ),
                      if (!_isLoading && _material != null)
                        Text(
                          'Generated by Gemini · tap cards to flip',
                          style: TextStyle(
                              color: Colors.grey.shade500,
                              fontSize: 11),
                        ),
                    ],
                  ),
                ),
                GestureDetector(
                  onTap: () => Navigator.pop(context),
                  child: Container(
                    padding: const EdgeInsets.all(6),
                    decoration: BoxDecoration(
                      color: Colors.grey.shade100,
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: const Icon(Icons.close_rounded,
                        color: Colors.grey, size: 18),
                  ),
                ),
              ],
            ),
          ),

          if (_isLoading)
            Padding(
              padding: const EdgeInsets.fromLTRB(20, 8, 20, 40),
              child: Column(
                children: [
                  const CircularProgressIndicator(
                      color: Color(0xFF035955)),
                  const SizedBox(height: 16),
                  Text(_statusMsg,
                      style: TextStyle(
                          color: Colors.grey.shade600, fontSize: 13)),
                ],
              ),
            )
          else if (_material == null)
            Padding(
              padding: const EdgeInsets.fromLTRB(20, 8, 20, 40),
              child: Column(
                children: [
                  Icon(Icons.info_outline_rounded,
                      color: Colors.grey.shade400, size: 40),
                  const SizedBox(height: 12),
                  Text(
                   'These photos haven\'t been indexed yet.\nOnly photos uploaded through the app can be studied.',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                        color: Colors.grey.shade500, fontSize: 13),
                  ),
                ],
              ),
            )
          else ...[
            Container(
              margin: const EdgeInsets.fromLTRB(20, 0, 20, 16),
              decoration: BoxDecoration(
                color: Colors.grey.shade100,
                borderRadius: BorderRadius.circular(12),
              ),
              child: TabBar(
                controller: _tabController,
                indicator: BoxDecoration(
                  color: const Color(0xFF035955),
                  borderRadius: BorderRadius.circular(10),
                ),
                labelColor: Colors.white,
                unselectedLabelColor: Colors.grey.shade600,
                labelStyle: const TextStyle(
                    fontWeight: FontWeight.bold, fontSize: 12),
                dividerColor: Colors.transparent,
                tabs: const [
                  Tab(text: 'Summary'),
                  Tab(text: 'Details'),
                  Tab(text: 'Flashcards'),
                ],
              ),
            ),
            ConstrainedBox(
              constraints: BoxConstraints(
                maxHeight: MediaQuery.of(context).size.height * 0.5,
              ),
              child: TabBarView(
                controller: _tabController,
                children: [
                  _buildBullets(),
                  _buildDetails(),
                  _buildFlashcards(),
                ],
              ),
            ),
            const SizedBox(height: 20),
          ],
        ],
      ),
    );
  }

  Widget _buildBullets() {
    final bullets = _material!.bullets;
    return ListView.builder(
      padding: const EdgeInsets.fromLTRB(20, 0, 20, 20),
      physics: const BouncingScrollPhysics(),
      itemCount: bullets.length,
      itemBuilder: (_, i) => Container(
        margin: const EdgeInsets.only(bottom: 10),
        padding: const EdgeInsets.all(14),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(12),
          border: Border.all(color: const Color(0xFFEEEEEE)),
          boxShadow: const [
            BoxShadow(
                color: Color(0x06000000),
                blurRadius: 6,
                offset: Offset(0, 2)),
          ],
        ),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Container(
              margin: const EdgeInsets.only(top: 2),
              width: 8,
              height: 8,
              decoration: const BoxDecoration(
                color: Color(0xFF035955),
                shape: BoxShape.circle,
              ),
            ),
            const SizedBox(width: 12),
            Expanded(
              child: Text(bullets[i],
                  style: const TextStyle(
                      fontSize: 13,
                      color: AppColors.bodyText,
                      height: 1.4)),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildDetails() {
    final details = _material!.details;
    return ListView.builder(
      padding: const EdgeInsets.fromLTRB(20, 0, 20, 20),
      physics: const BouncingScrollPhysics(),
      itemCount: details.length,
      itemBuilder: (_, i) => Container(
        margin: const EdgeInsets.only(bottom: 12),
        padding: const EdgeInsets.all(14),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(12),
          border: Border.all(color: const Color(0xFFEEEEEE)),
          boxShadow: const [
            BoxShadow(
                color: Color(0x06000000),
                blurRadius: 6,
                offset: Offset(0, 2)),
          ],
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Container(
              padding:
                  const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
              decoration: BoxDecoration(
                color: const Color(0xFF89B0AE).withOpacity(0.12),
                borderRadius: BorderRadius.circular(6),
              ),
              child: Text(
                'Point ${i + 1}',
                style: const TextStyle(
                    color: Color(0xFF035955),
                    fontSize: 10,
                    fontWeight: FontWeight.bold),
              ),
            ),
            const SizedBox(height: 8),
            Text(details[i],
                style: TextStyle(
                    fontSize: 13,
                    color: Colors.grey.shade700,
                    height: 1.5)),
          ],
        ),
      ),
    );
  }

  Widget _buildFlashcards() {
    final cards = _material!.flashcards;
    return ListView.builder(
      padding: const EdgeInsets.fromLTRB(20, 0, 20, 20),
      physics: const BouncingScrollPhysics(),
      itemCount: cards.length,
      itemBuilder: (_, i) {
        final isFlipped = _flippedIndex == i;
        return GestureDetector(
          onTap: () {
            HapticFeedback.selectionClick();
            setState(() => _flippedIndex = isFlipped ? -1 : i);
          },
          child: AnimatedContainer(
            duration: const Duration(milliseconds: 250),
            margin: const EdgeInsets.only(bottom: 10),
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: isFlipped
                  ? const Color(0xFF035955)
                  : Colors.white,
              borderRadius: BorderRadius.circular(14),
              border: Border.all(
                color: isFlipped
                    ? const Color(0xFF035955)
                    : const Color(0xFFEEEEEE),
              ),
              boxShadow: [
                BoxShadow(
                    color: isFlipped
                        ? const Color(0x44035955)
                        : const Color(0x08000000),
                    blurRadius: isFlipped ? 10 : 6,
                    offset: const Offset(0, 2)),
              ],
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    Container(
                      padding: const EdgeInsets.symmetric(
                          horizontal: 7, vertical: 3),
                      decoration: BoxDecoration(
                        color: isFlipped
                            ? Colors.white.withOpacity(0.2)
                            : const Color(0xFF89B0AE).withOpacity(0.12),
                        borderRadius: BorderRadius.circular(6),
                      ),
                      child: Text(
                        isFlipped ? 'Answer' : 'Q${i + 1}',
                        style: TextStyle(
                            color: isFlipped
                                ? Colors.white
                                : const Color(0xFF035955),
                            fontSize: 10,
                            fontWeight: FontWeight.bold),
                      ),
                    ),
                    const Spacer(),
                    Icon(
                      isFlipped
                          ? Icons.flip_rounded
                          : Icons.touch_app_rounded,
                      size: 14,
                      color: isFlipped
                          ? Colors.white60
                          : Colors.grey.shade400,
                    ),
                  ],
                ),
                const SizedBox(height: 10),
                Text(
                  isFlipped ? cards[i].answer : cards[i].question,
                  style: TextStyle(
                      fontSize: 13,
                      color: isFlipped
                          ? Colors.white
                          : AppColors.bodyText,
                      height: 1.4,
                      fontWeight: FontWeight.w500),
                ),
              ],
            ),
          ),
        );
      },
    );
  }
}